export enum JobApplicationStatus {
  WISHLIST = "WISHLIST",
  APPLIED = "APPLIED",
  SCREENING = "SCREENING",
  INTERVIEW = "INTERVIEW",
  ASSESSMENT = "ASSESSMENT",
  OFFER = "OFFER",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}

export enum EmploymentType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  CONTRACT = "CONTRACT",
  INTERNSHIP = "INTERNSHIP",
  FREELANCE = "FREELANCE",
}

export enum JobSource {
  LINKEDIN = "LINKEDIN",
  INDEED = "INDEED",
  COMPANY_WEBSITE = "COMPANY_WEBSITE",
  REFERRAL = "REFERRAL",
  JOB_BOARD = "JOB_BOARD",
  OTHER = "OTHER",
}